### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [polodarb/Flashlight-Tiramisu#1] opened 2022-08-19 12:03 UTC
Hi,

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app in F-Droid by yourself, would you still agree with the inclusion of your app in F-Droid by the maintainer team?

**Comment by licaon-kter** [comment] 2022-09-27 14:46
;) pls test https://gitlab.com/fdroid/rfp/-/issues/2217#note_1116002575

Also, small request, can you bump gradle to 7.5 since that's released: https://github.com/polodarb/Flashlight-Tiramisu/blob/main/gradle/wrapper/gradle-wrapper.properties#L3 ?

**Comment by polodarb** [comment] 2022-10-04 09:31
> ;) pls test https://gitlab.com/fdroid/rfp/-/issues/2217#note_1116002575
> 
> Also, small request, can you bump gradle to 7.5 since that's released: https://github.com/polodarb/Flashlight-Tiramisu/blob/main/gradle/wrapper/gradle-wrapper.properties#L3 ?

Hi :)
Gradle I updated to the 8th version. But I did not understand what exactly needs to be checked in the first link that you wrote 🤔

**Comment by licaon-kter** [comment] 2022-10-04 09:33
@polodarb get the APK and install and test... from that link...

**Comment by polodarb** [comment] 2022-10-04 10:07
oh ok, the application works, but you need to remove the permission for the camera, it is superfluous

**Comment by licaon-kter** [comment] 2022-10-04 14:31
@polodarb We're ready: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11839

All we need is a Fastlane folder structure to hold description, icon, summary, screenshots, changelogs: https://gitlab.com/-/snippets/1895688

**Comment by polodarb** [comment] 2022-10-07 18:21
> 

Okay, but please give me some time, I've never worked with Fastlane before :)

**Comment by licaon-kter** [comment] 2022-10-08 14:56
@polodarb as I said, you don't work with Fastlane tools, just create the folders and files ;)

**Comment by polodarb** [comment] 2022-10-08 15:35
>

Please check if I did it right

**Comment by licaon-kter** [comment] 2022-11-03 11:06
@polodarb sorry for the delay

Rename this to `icon.png` https://github.com/polodarb/Flashlight-Tiramisu/blob/main/fastlane/metadata/android/en-US/images/app_icon.png

Rename this to `1.txt` (it's the versionCode not Name ;)) https://github.com/polodarb/Flashlight-Tiramisu/blob/main/fastlane/metadata/android/en-US/changelogs/1.0.txt

**Comment by polodarb** [comment] 2022-11-03 11:16
@licaon-kter done :)

**Comment by licaon-kter** [comment] 2022-11-04 08:50
DOne :)

**Comment by licaon-kter** [comment] 2022-11-04 09:40
@polodarb chances are that the app is build reproducible, can you provide a signed APK for commit baf842b3edfd6b319d68a6c66aea3eadbd94cf3e ?

**Comment by polodarb** [comment] 2022-11-09 11:51
@licaon-kter Thank you so much for posting in FDroid ❤️
On account of the last comment - I will publish an update soon

**Comment by polodarb** [comment] 2022-11-25 14:09
@licaon-kter Hello, how do I update the app in F-Droid?

**Comment by licaon-kter** [comment] 2022-11-25 14:35
It will be picked up by the Checkupdate bot soon ;)

**Comment by polodarb** [comment] 2022-11-25 14:43
Oh, okay, thanks :)

**Closed** 2022-12-04 18:49 UTC
